theme: jekyll-theme-slate
name: Something Witty
description: Something witty... from Jesse's head, more precisely.
author: Jesse
author_email: rotenberg.jesse@gmail.com
baseurl:
url: http://jrotenberg.me/^M
permalink: pretty^M
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]^M
